### ISSUE TITLE
Stopping the memory drivers is messy/broken

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#178]
Especially the peer store. If we do make a change in the architecture, I'll have to come up with something better that's also not horrible on performance or readability.
As of right now it's broken, this is what happens if you stop a tracker that is in use:

```
^C2016/06/21 09:06:04 Store server shut down cleanly
2016/06/21 09:06:04 Prometheus server shut down cleanly
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39873: attempted to interact with stopped store
goroutine 435692 [running]:
net/http.(*conn).serve.func1(0xc8203b6e00)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc820427620)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82042760c, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc82007abd0, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82042760c, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc82007abd0, 0xc820398550, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc82007abd0, 0xc82007abd0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc82053b380, 0xc82050b340, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc82053b380, 0xc82050b340, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc82053b380, 0xc82050b340)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc82053b380, 0xc82050b340)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203b6e00)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39874: attempted to interact with stopped store
goroutine 435693 [running]:
net/http.(*conn).serve.func1(0xc8203b6e80)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc8201cd410)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc8201cd3fc, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc8203caa20, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc8201cd3fc, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc8203caa20, 0xc8200787d0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc8203caa20, 0xc8203caa20, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc820524a90, 0xc8204af180, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc820524a90, 0xc8204af180, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc820524a90, 0xc8204af180)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc820524a90, 0xc8204af180)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203b6e80)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39875: attempted to interact with stopped store
goroutine 435233 [running]:
net/http.(*conn).serve.func1(0xc8203b7100)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc82055cd10)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82055ccfc, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc8203ce870, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82055ccfc, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc8203ce870, 0xc8201865f0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc8203ce870, 0xc8203ce870, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc820528a90, 0xc8203847e0, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc820528a90, 0xc8203847e0, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc820528a90, 0xc8203847e0)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc820528a90, 0xc8203847e0)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203b7100)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39876: attempted to interact with stopped store
goroutine 435874 [running]:
net/http.(*conn).serve.func1(0xc82055a400)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc8202f6150)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc8202f614c, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc820318240, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc8202f614c, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc820318240, 0xc8205ee1e0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc820318240, 0xc820318240, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc8202e4340, 0xc82042a000, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc8202e4340, 0xc82042a000, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc8202e4340, 0xc82042a000)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc8202e4340, 0xc82042a000)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82055a400)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39868: attempted to interact with stopped store
goroutine 435691 [running]:
net/http.(*conn).serve.func1(0xc82009d980)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc820427670)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82042766c, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc82007acf0, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82042766c, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc82007acf0, 0xc8203985a0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc82007acf0, 0xc82007acf0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc82053b5f0, 0xc820384620, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc82053b5f0, 0xc820384620, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc82053b5f0, 0xc820384620)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc82053b5f0, 0xc820384620)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82009d980)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39855: attempted to interact with stopped store
goroutine 435828 [running]:
net/http.(*conn).serve.func1(0xc82051a580)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc8204276c0)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc8204276bc, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc82007ad80, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc8204276bc, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc82007ad80, 0xc8203985f0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc82007ad80, 0xc82007ad80, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc82053b790, 0xc820386540, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc82053b790, 0xc820386540, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc82053b790, 0xc820386540)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc82053b790, 0xc820386540)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82051a580)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 http: panic serving 127.0.0.1:39860: attempted to interact with stopped store
goroutine 435829 [running]:
net/http.(*conn).serve.func1(0xc82051a600)
        /opt/go/latest/src/net/http/server.go:1389 +0xc1
panic(0x7dc9e0, 0xc820427720)
        /opt/go/latest/src/runtime/panic.go:443 +0x4e9
github.com/chihaya/chihaya/server/store/memory.(*peerStore).PutLeecher(0xc8200fd600, 0xc519665d1940cb10, 0xcafc71185eb20c52, 0x67b9812d, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82042770c, 0x4, 0x4, ...)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/memory/peer_store.go:162 +0x278
github.com/chihaya/chihaya/server/store/middleware/swarm.updatePeerStore(0xc82007ae10, 0x2d3436454b4f502d, 0x3130303030303030, 0x31313134, 0xc82042770c, 0x4, 0x4, 0x371f, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:68 +0x262
github.com/chihaya/chihaya/server/store/middleware/swarm.announceSwarmInteraction.func1(0xc82006cb40, 0xc82007ae10, 0xc820398640, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/store/middleware/swarm/swarm.go:30 +0x107
github.com/chihaya/chihaya/tracker.(*Tracker).HandleAnnounce(0xc8200fcee0, 0xc82007ae10, 0xc82007ae10, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/tracker/tracker.go:71 +0x79
github.com/chihaya/chihaya/server/http.(*httpServer).serveAnnounce(0xc8200fdaa0, 0x7f734cc85130, 0xc82053b930, 0xc8200a57a0, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:107 +0xa9
github.com/chihaya/chihaya/server/http.(*httpServer).(github.com/chihaya/chihaya/server/http.serveAnnounce)-fm(0x7f734cc85130, 0xc82053b930, 0xc8200a57a0, 0x0, 0x0, 0x0)
        /media/data/go/src/github.com/chihaya/chihaya/server/http/server.go:95 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82017a040, 0x7f734cc85130, 0xc82053b930, 0xc8200a57a0)
        /media/data/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.serverHandler.ServeHTTP(0xc8201a6080, 0x7f734cc85130, 0xc82053b930, 0xc8200a57a0)
        /opt/go/latest/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82051a600)
        /opt/go/latest/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/latest/src/net/http/server.go:2137 +0x44e
2016/06/21 09:06:04 HTTP server shut down cleanly
```

This can be circumvented by moving the `store` server in the config after the `http` server. Then again, that could cause `store middleware used without store server` panics during startup.

**Comment by jzelinskie** [comment]
@mrd0ll4r is this still the case on master? I don't think so.

**Comment by mrd0ll4r** [comment]
You're right, fixed in master, closing! :)
