### ISSUE TITLE
Peer store panics on creation with old (a few days) config

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#319]
This is because the prometheus reporting interval was added in the config.
If unspecified, it defaults to zero. This causes a panic in the initialization of the peer store like this:

```
panic: non-positive interval for NewTicker

goroutine 36 [running]:
time.NewTicker(0x0, 0x913b38)
	/usr/lib/go/src/time/tick.go:23 +0x1b4
github.com/chihaya/chihaya/storage/memory.New.func3(0xc420075e40, 0xc393e6d000, 0x0, 0xdf84758000, 0x400)
	<->/github.com/chihaya/chihaya/storage/memory/peer_store.go:128 +0x73
created by github.com/chihaya/chihaya/storage/memory.New
	<->/github.com/chihaya/chihaya/storage/memory/peer_store.go:140 +0x2fa
```

Fix is simple, just add a check and possible a default value of 1, same way as the encryption key used for UDP...

**Comment by mrd0ll4r** [comment]
@cedricgc do you wannt to/have time to work on this?

**Comment by cedricgc** [comment]
I should have time this weekend. I will follow up on IRC later.

**Comment by cedricgc** [comment]
Yeah I can do this.

**Comment by mrd0ll4r** [comment]
I can't assign you to this issue, but I'll be happy to review a PR :)

**Comment by cedricgc** [comment]
reproduced error by removing value from config:

```bash
docker run --rm -v $(pwd):/tmp cedricgc/chihaya --config /tmp/example_config.yaml
time="2017-06-03T18:36:48Z" level=info msg="starting Prometheus server" addr="0.0.0.0:6880"
time="2017-06-03T18:36:48Z" level=info msg="starting storage" gcInterval=14m0s peerLifetime=16m0s shardCount=1024
time="2017-06-03T18:36:48Z" level=info msg="starting middleware" postHooks=[] preHooks=[]
time="2017-06-03T18:36:48Z" level=info msg="starting HTTP frontend" addr="0.0.0.0:6881" allowIPSpoofing=false enableRequestTiming=false readTimeout=5s realIPHeader=x-real-ip tlsCertPath= tlsKeyPath= writeTimeout=5s
time="2017-06-03T18:36:48Z" level=info msg="starting UDP frontend" addr="0.0.0.0:6881" allowIPSpoofing=false enableRequestTiming=false maxClockSkew=10s privateKey="paste a random string here that will be used to hmac connection IDs"
panic: non-positive interval for NewTicker

goroutine 42 [running]:
time.NewTicker(0x0, 0x916f30)
	/usr/local/go/src/time/tick.go:23 +0x1b4
github.com/chihaya/chihaya/storage/memory.New.func3(0xc420130cc0, 0xc393e6d000, 0x0, 0xdf84758000, 0x400)
	/go/src/github.com/chihaya/chihaya/storage/memory/peer_store.go:128 +0x73
created by github.com/chihaya/chihaya/storage/memory.New
	/go/src/github.com/chihaya/chihaya/storage/memory/peer_store.go:140 +0x2fa
```
