### ISSUE TITLE
panic parsing HTTP query

### ISSUE THREAD

**Issue by Aranjedeath** [chihaya/chihaya#334]
```
2017/06/05 15:50:33 http: panic serving IP:PORT: runtime error: slice bounds out of range
goroutine 3631164058 [running]:
net/http.(*conn).serve.func1(0xc46e1bb680)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x87aba0, 0xb28810)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/chihaya/chihaya/bittorrent.parseQuery(0xc46f4b180c, 0x7b0, 0x8f7f4d, 0x1, 0x7)
        /home/explodie/GOPATH/src/github.com/chihaya/chihaya/bittorrent/params.go:119 +0x57a
github.com/chihaya/chihaya/bittorrent.ParseURLData(0xc46f4b1804, 0x7b8, 0xc479f13420, 0xc4483e7b28, 0x4292fe)
        /home/explodie/GOPATH/src/github.com/chihaya/chihaya/bittorrent/params.go:81 +0x79
github.com/chihaya/chihaya/frontend/http.ParseScrape(0xc48a7fd600, 0x914d58, 0xc474d39200, 0xc4483e7b98)
        /home/explodie/GOPATH/src/github.com/chihaya/chihaya/frontend/http/parser.go:87 +0x42
github.com/chihaya/chihaya/frontend/http.(*Frontend).scrapeRoute(0xc474d39200, 0xb03620, 0xc4700c7340, 0xc48a7fd600, 0x0, 0x0, 0x0)
        /home/explodie/GOPATH/src/github.com/chihaya/chihaya/frontend/http/frontend.go:225 +0xbf
github.com/chihaya/chihaya/frontend/http.(*Frontend).(github.com/chihaya/chihaya/frontend/http.scrapeRoute)-fm(0xb03620, 0xc4700c7340, 0xc48a7fd600, 0x0, 0x0, 0x0)
        /home/explodie/GOPATH/src/github.com/chihaya/chihaya/frontend/http/frontend.go:144 +0x66
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc474d5ff40, 0xb03620, 0xc4700c7340, 0xc48a7fd600)
        /home/explodie/GOPATH/src/github.com/julienschmidt/httprouter/router.go:344 +0x813
net/http.serverHandler.ServeHTTP(0xc452e889a0, 0xb03620, 0xc4700c7340, 0xc48a7fd600)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc46e1bb680, 0xb03fa0, 0xc458fc9dc0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by mrd0ll4r** [comment]
Whoops, referenced some random PR instead of this issue in the PR... should be fixed now :)
